### ISSUE TITLE
Flying Fish Bugs

### ISSUE THREAD

**Issue by Aranduran** [Ryorama/Terrariamod#4]
In v1.1 for Minecraft 1.14, flying fish have some issues that make them incredibly powerful
Flying fish spawn regardless of weather instead of only during rain. They also have a tendency to swarm compared to being an uncommon occurance
Flying fish are too small to effectively hit (consider they are the same size as the player in Terraria)
Flying fish fly through blocks to chase down the player (they can be heard suffocating)

**Comment by Ryorama** [comment]
Thanks for the report! I haven't really touched them in a while, but I will have to fix it. Quick question though, you said they spawn regardless of weather right? Because they don't for so unless I really screwed something up that shouldn't happen. If you fine with it, try turning off the doWeatherCycle gamerule temporarily just to make sure they aren't just being removed after it stops raining rather than still spawning.

**Comment by Aranduran** [comment]
I've yet to see it actually rain in this world.

**Comment by Ryorama** [comment]
Hmmm, odd. I will have to check that out

**Comment by Aranduran** [comment]
It does occur to me that there is a section of the world near spawn that is covered with normal snow, but I'm not sure if that happens in vanilla when it snows or just sporadically in the right biome. I've never seen any actual precipitation in-game though.

I don't want to flood you with a bunch of new github issues, but there are some other unusual things I've noticed or just simple QoL improvements/suggestions. Do you have somewhere people can send you suggestions and observations?

Thanks!

**Comment by Aranduran** [comment]
I might be wrong about the rain, I came across a section only a few blocks wide where it was raining just now. One block outside of that I can't even look back and see it raining. I also see it snowing consistently in a snow biome I discovered a few minutes ago. So maybe the rain is just not rendering in some biomes (not deserts) as expected for me? I'll test with some commands and get back to you.

**Comment by Ryorama** [comment]
Yeah, a while ago when making the biomes I screwed up and made them all cold biomes. I’ve only fixed a few of them, but never got around to fixing the rest.

**Comment by Aranduran** [comment]
Sorry for disappearing. I notice that there are small patches of the world (like maybe 5 block radius) where it rains, but commands don't let me turn off the rain. I also notice it does seem to always snow in the winter biome.
I've pretty much given up with this mod, for now, sorry to say (I was really enjoying it for a while) because of a separate game breaking issue (opening a new issue rather than putting the details here).

**Comment by Ryorama** [comment]
It's fine, as I mentioned in the other issue I'm discounting the 1.14.4 version as it has a ton of bugs and it's just not worth trying to fix at this point. I might think about doing a bug fix at the point, but right now it's not on my priority list I'm sorry for any inconvenience that this may have caused. If you find any more issues and either versions, feel free to open a bug report regardless whether I do the 1.14.4 bugfix, because if I do I want to fix as many as I can or maybe someone else could possibly fix them in the future. I will be closing this issue as well, but if you need you can reopen either of the issues with more details and I will look into them!
